server:
  port: 8082
database:
  mode: memory
cache:
  mode: memory
blob:
  mode: memory
initialTenant:
  slug: raccoons
  name: Raccoons
  oidc:
    client: dockyard-app
    issuer: http://localhost:8081/oidc/keyline
    roleClaim: roles
    roleClaimFormat: array
    roleClaimMapping:
      "dockyard:admin": admin
      "dockyard:project-admin": project-admin
      "dockyard:developer": developer