server:
  port: 8082
database:
  mode: memory
cache:
  mode: memory
blob:
  mode: memory
initialTenant:
  slug: raccoons
  name: Raccoons
  oidc:
    client: dockyard-app
    issuer: http://localhost:8081/oidc/keyline
    roleClaim: roles
    roleClaimFormat: array
    roleClaimMapping:
      admin: dockyard:admin
      project-admin: dockyard:project-admin
      developer: dockyard:developer