server:
  port: 8082
database:
  mode: postgres
  postgres:
    host: localhost
    port: 5788
    username: user
    password: password
    sslMode: disable
cache:
  mode: memory
blob:
  mode: memory
kms:
  mode: memory
initialTenant:
  slug: raccoons
  name: Raccoons
  oidc:
    client: dockyard-app
    issuer: http://localhost:8081/oidc/keyline
    roleClaim: roles
    roleClaimFormat: array
    roleClaimMapping:
      "dockyard:admin": admin
      "dockyard:project-admin": project-admin
      "dockyard:developer": developer
